steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'northamerica-northeast1.pkg.dev/nklab-415204/nishad-flask-image:$COMMIT_SHA', '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'northamerica-northeast1.pkg.dev/nklab-415204/nishad-flask-image:$COMMIT_SHA']

  # Deploy Docker container to Cloud Run using Google Cloud SDK
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy kushal-image \
          --image northamerica-northeast1.pkg.dev/nklab-415204/nishad-flask-image:$COMMIT_SHA \
          --platform managed \
          --region northamerica-northeast1

images:
  - 'northamerica-northeast1.pkg.dev/nklab-415204/nishad-flask-image:$COMMIT_SHA'
  
options:
    defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

#Adding comment
